ENERGISA_TERMS = {
    "critico": [
        "incêndio",
        "fogo",
        "explosão",
        "faísca",
        "arco elétrico",
        "choque elétrico",
        "descarga elétrica",
        "condutor energizado no solo",
        "fio energizado no chão",
        "rede energizada caída",
        "cabo energizado rompido",
        "hospital",
        "escola",
        "creche",
        "unidade de saúde",
        "posto de saúde",
        "área escolar",
        "pessoa próxima à rede energizada",
        "pedestre próximo ao fio",
        "população exposta",
        "risco iminente à vida"
    ],

    "alto": [
        "fio energizado",
        "fio exposto",
        "condutor rompido",
        "poste inclinado",
        "poste caído",
        "poste com risco de queda",
        "rede baixa",
        "rede rompida",
        "via pública",
        "calçada",
        "rua movimentada",
        "avenida",
        "cruzamento",
        "poste atingido por veículo",
        "colisão em poste",
        "acidente de trânsito com poste",
        "transformador vazando óleo",
        "transformador com ruído",
        "transformador superaquecido",
        "área urbana",
        "zona urbana",
        "proximidade de residências"
    ],

    "medio": [
        "poste danificado",
        "poste rachado",
        "poste com fissura",
        "isolador quebrado",
        "isolador danificado",
        "transformador",
        "caixa de medição danificada",
        "equipamento elétrico danificado",
        "vegetação próxima",
        "galhos próximos à rede",
        "árvore encostando na rede",
        "necessidade de manutenção",
        "manutenção preventiva",
        "inspeção necessária",
        "área rural",
        "estrada vicinal"
    ],

    "baixo": [
        "situação normal",
        "sem risco",
        "sem risco imediato",
        "rede regular",
        "rede em boas condições",
        "poste em boas condições",
        "inspeção visual",
        "vistoria rotineira",
        "manutenção concluída",
        "sem anormalidades",
        "operação normal",
        "funcionamento regular"
    ]
}